const GET_USERS = "GET_USERS";
const CREATE_USER = "CREATE_USER";
const REQUEST_USERS = "REQUEST_USERS";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";

export { GET_USERS, CREATE_USER, REQUEST_USERS, UPDATE_USER, DELETE_USER };
